tester fixed

diff --git a/scripts/tester b/scripts/tester
--- a/scripts/tester
+++ b/scripts/tester
@@ -1,13 +1,26 @@
 #!/bin/bash
+if [ $# -ne 2 ]; then
+  # Print usage
+  echo 'Error! wrong number of arguments'
+  echo 'usage:'
+  echo "$0 cluster_name cluster_version"
+  echo 'e.g.'
+  echo "$0 stacked 1.12.3"
+  exit 1
+fi
 TMP=$(mktemp -d)
 this_test=$1
+this_kube_ver=$2
 
 # delete the cluster
 kubash -n $this_test decommission -y
 rm -Rf ~/.kubash/clusters/$this_test
 
 # prep for the cluster
-envsubst ~/.kubash/examples/$this_test.tpl > $TMP/cluster.yaml
+REPLACEME_OS_TPL=$this_kube_ver \
+envsubst \
+    < ~/.kubash/examples/$this_test.tpl \
+    > $TMP/cluster.yaml
 kubash yaml2cluster -n $this_test $TMP/cluster.yaml
 rm $TMP/cluster.yaml
 
